name: build wheels

on: [workflow_dispatch]
# on:
#   push:
#     tags:
#       - "v*"

jobs:
  build-wheels:
    name: Build
    strategy:
      matrix:
        platform: [ ubuntu-20.04 ]
        # platform: [ ubuntu-20.04, macos-10.15 ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==2.12.3
    - name: Build wheel
      env:
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_BEFORE_ALL: "bash .github/workflows/prepare_cibuildwheel.sh"
        CIBW_BEFORE_BUILD: "pip install setuptools-rust==0.10.6"
        CIBW_BUILD: "cp37-* cp38-*" #"cp36-* cp37-* cp38-*"
        CIBW_ENVIRONMENT: PATH="$HOME/.cargo/bin:$PATH"
        CIBW_SKIP: "*_i686 *musllinux*"
        CIBW_TEST_COMMAND: "magpurify2 --help"
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: wheels-artifact
        path: wheelhouse
