name: build wheels

on: [push]
# on:
#   push:
#     tags:
#       - "v*"

jobs:
  build-wheels:
    name: Build
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        python-version: "3.8"
    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.3.0
    - name: Build wheel
      env:
        CIBW_BEFORE_BUILD: "bash .github/workflows/prepare_build.sh"
        CIBW_BUILD: "cp36-* cp37-* cp38-*"
        CIBW_ENVIRONMENT: PATH="$HOME/.cargo/bin:$PATH"
        CIBW_SKIP: "*_i686"
        CIBW_TEST_COMMAND: "magpurify2 --help"
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build-artifact
        path: wheelhouse
