name: deploy website

on: [push]

jobs:
  deploy-website:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
      - name: Build
        shell: bash
        run: bash .github/workflows/build_website.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: website/.vuepress/dist
